//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopDongCSHT.HDContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSHT_QNHEntities : DbContext
    {
        public CSHT_QNHEntities()
            : base("name=CSHT_QNHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HopDong> HopDongs { get; set; }
        public virtual DbSet<Luu_File> Luu_File { get; set; }
        public virtual DbSet<Map_HD_File> Map_HD_File { get; set; }
    }
}
