//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopDongCSHT.HDContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        public int ID { get; set; }
        public string SoHopDong { get; set; }
        public string Ten_HD { get; set; }
        public string LoaiHD { get; set; }
        public string CSHT_DiaChi { get; set; }
        public string Ten_A { get; set; }
        public string A_DiaChi { get; set; }
        public string A_DienThoai { get; set; }
        public string A_MST { get; set; }
        public string A_DaiDien { get; set; }
        public string A_ChucVu { get; set; }
        public Nullable<int> ThoiGianThue { get; set; }
        public System.DateTime TuNgay { get; set; }
        public System.DateTime DenNgay { get; set; }
        public Nullable<double> DonGia { get; set; }
    }
}
