//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopDongCSHT.HDContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luu_File
    {
        public int ID { get; set; }
        public string Ten_File { get; set; }
        public string Duong_dan { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
