//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopDongCSHT.HDContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map_HD_File
    {
        public int ID { get; set; }
        public Nullable<int> HD_ID { get; set; }
        public Nullable<int> File_ID { get; set; }
        public Nullable<int> ColOrder { get; set; }
    }
}
